### ISSUE TITLE
previo consulta( con procedimiento almacenado en mysql desde python ) y posible plot

### ISSUE THREAD

**Issue by georginaguilar** [georginaguilar/Kinect_Enero2016#2]
[muestra.txt](https://github.com/georginaguilar/Kinect_Enero2016/files/135262/muestra.txt)

**Comment by mariosky** [comment]
Quedamos que ibas a describir las consultas, no slo poner el SQL y ya.

Y el tiempo?

**Comment by mariosky** [comment]
Muestrame el sp_consulaTest

2016-02-17 14:31 GMT-08:00 mario garcia mariosky@gmail.com:

**Comment by georginaguilar** [comment]
describir las consultas?, las consultas las tenia como consulta simple en el script ahi hacia la consulta y es por eso que decidi hacer el store procedure porque no pude hacer que la consulta compuestas funcionaran pero recorde esa parte y la aplique no se si sea correcta o si se pueda hacer ese procedimiento directamente en el script de python.....

el tiempo se refiere a la consulta en donde veo las capturas por minuto en cada experimento?

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_noCapturasT`()
BEGIN
SELECT clave_unica,date_format(fecha,'%H:%i'), HOUR(fecha), MINUTE(fecha), count(distinct No_Usuarios )
FROM  extradata_capturev9_videos v
group by clave_unica,date_format(fecha,'%H:%i'), HOUR(fecha),MINUTE(fecha);
END;

RESULTADO:

('35134F9E-E278-4F01-8161-52EB012FD7BC', '16:59', 16L, 59L, 1L)
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:00', 17L, 0L, 4L)
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:01', 17L, 1L, 3L)
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:02', 17L, 2L, 3L)
('5188C42D-57B0-4567-AB0C-08D99446348E', '13:59', 13L, 59L, 2L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:16', 16L, 16L, 2L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:17', 16L, 17L, 5L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:18', 16L, 18L, 3L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:19', 16L, 19L, 3L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:20', 16L, 20L, 2L)
('53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE', '16:21', 16L, 21L, 2L)
('568FC4A3-FB58-4C12-A2E2-A2E229994BFA', '14:07', 14L, 7L, 5L)
('568FC4A3-FB58-4C12-A2E2-A2E229994BFA', '14:08', 14L, 8L, 2L)
('568FC4A3-FB58-4C12-A2E2-A2E229994BFA', '14:09', 14L, 9L, 2L)

# 

# sp_consulaTest

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_consulaTest`()
BEGIN
SELECT clave_unica,engage,count(_), (select count(_) from extradata_capturev9_videos where clave_unica = v.clave_unica  ),count(_) / (select count(_) from extradata_capturev9_videos where clave_unica = v.clave_unica  )
FROM  extradata_capturev9_videos v
WHERE engage='Yes' AND
clave_unica IN ('35134F9E-E278-4F01-8161-52EB012FD7BC','53A02C94-D461-4DB7-8F9A-2EFD81EAC8CE','568FC4A3-FB58-4C12-A2E2-A2E229994BFA',
'6094848F-4E6A-49EB-8D7D-3287D36CB053','6DECB12D-68F2-48EB-8243-F85781F0CB41','7C612517-865A-4CBD-BCC6-35074F897497',
'7DEFD876-AC96-4C74-B11A-960B44B0EA37','A221E72E-98B2-431A-854B-260D5A4E7D46','A3A75BBD-C429-4B16-AA37-417DE7B17158',
'AB4D71D6-79BB-48DB-A447-5F96899F2CBB','C589A7D0-8228-47CA-A7AF-478C3EDB9538','CC3DE67E-AE9A-4B92-A5BF-5D7CD3BE4B98',
'FA19AD21-1A34-456A-BE60-E66A3DF64AB5','Yes')
group by clave_unica, engage;
END;

aqui me crea la duda solo lo estoy limitando a solo estas claves de usuarios pero si quisiera que tomara todas las registradas ya que están filtradas en esta misma consulta, solo se pondria poner solo engage='Yes' and clave_usuario(tengo confusión  aqui para que me tome todos los capurados)

WHERE engage='Yes' AND
clave_unica

**Comment by mariosky** [comment]
Ok

clave_unica es el XBOX

Debes hacer los plots por Tiempo
Elimina de la base de datos los ID que tengan muy pocas lecturas

2016-02-17 16:42 GMT-08:00 georginaguilar notifications@github.com:

**Comment by georginaguilar** [comment]
existe  otra manera de cambiar el nombre para la clave unica como se habia pensado que no sea como esta:

update data_capturev5
    set clave_unica="Grupo1"
    where clave_unica ="30D4DA1B-267F-46B8-82C7-2C1F4B31924D"

por que en la clave única se tendría que especificar cada clave única, es correcto?, y he tratado cambiar los tiempos y ponerlos continuos como menciono la vez pasada..... es decir que quedaran que se asigne el numero 1 a la captura que se realizo a las 5:10, por ejemplo asignar el numero 2 a la captura realizada a las 5:15 y así sucesivamente.., el numero del tiempo no lo he podido asignar

ejemplo:
experimento
clave_unica            hora de captura            tiempo   total de personas capturadas  
    1                          15:10                          1
    1                          15:15                          2
    1                          15:47                          3
    2                          17:00                          1  
    2                          17:02                          2 

o solo es por el momento para poderlos agrupar de acuerdo al experimento?

**Comment by mariosky** [comment]
Lo del id se puede con un script, el tiempo cambialo a un entero por
ejemplo
02:34. ---> 10234

**Comment by georginaguilar** [comment]
Hice el cambio de la hora a minutos.... quedo algo así, aun no he podido resolver la duda de el agrupamiento de los elementos y la asignación de el posicionamiento a cada grupo...

SCRIPT

#!/usr/bin/python
 # -_\- coding: latin-1 -_-
 # -_\- coding: utf-8 -_

import MySQLdb

# Variable con la configuracion de la conexion

config_mysql = MySQLdb.Connect('localhost', 'localhost', '1234', 'kf_json')

# conectamos al servidor MySql

cursor = config_mysql.cursor()

#experiment
result2 = cursor.execute("call sp_noCapturasT()")
result3 = cursor.fetchall()

listaDePromedios = []
cont = 0

for resultind in result3:
    print resultind
    print 'Posicion #: %s' % (len(listaDePromedios)) #cuenta los registros
    #las horas las convierte a minutos
    conv1h=(resultind[2]*3600)
    conv2m=(conv1h+resultind[3])
    print 'Minutos: %s' % (conv2m)
    listaDePromedios.append(resultind[4])
    #print listaDePromedios.count(resultind[4])

cursor.fetchall()

# Cerramos la variable encargada de las consultas

cursor.close()

# Cerramos la conexión

config_mysql.close()

RESULTADO

('35134F9E-E278-4F01-8161-52EB012FD7BC', '16:59', 16L, 59L, 1L)
Posicion #: 0
Minutos: 57659
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:00', 17L, 0L, 4L)
Posicion #: 1
Minutos: 61200
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:01', 17L, 1L, 3L)
Posicion #: 2
Minutos: 61201
('35134F9E-E278-4F01-8161-52EB012FD7BC', '17:02', 17L, 2L, 3L)
Posicion #: 3
Minutos: 61202
